version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${RAILS_DATABASE_PASSWORD}
      MYSQL_USER: ${RAILS_DATABASE_USER}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec puma -C /app_name/config/puma.rb
    volumes:
      - .:/app_name
      - public-data:/app_name/public
      - tmp-data:/app_name/tmp
      - log-data:/app_name/log
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db

  nginx:
    build: containers/nginx
    volumes:
      - public-data:/app_name/public
      - tmp-data:/app_name/tmp
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: