version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec puma -C /sagittarius/config/puma.rb
    volumes:
      - .:/sagittarius
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RAILS_ENV: 'production'
    # environment:
    #   - RAILS_SYSTEM_TESTING_SCREENSHOT=inline
    tty: true

    build: 
      context: containers/nginx
    volumes:
      - public-data:/sagittarius/public
      - tmp-data:/sagittarius/tmp  
    ports:
      - "80:80"
    depends_on:
      - web
