version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${RAILS_DATABASE_PASSWORD}
      MYSQL_USER: ${RAILS_DATABASE_USER}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "4306:3306"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
      - public-data:/app_name/public
      - tmp-data:/app_name/tmp
      - log-data:/app_name/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: