version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec puma -C /sagittarius/config/puma.rb
    volumes:
      - .:/sagittarius
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RAILS_ENV: 'production'
    # environment:
    #   - RAILS_SYSTEM_TESTING_SCREENSHOT=inline
    tty: true

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
  
#   nginx:
#     build: 
#       context: containers/nginx
#     volumes:
#       - public-data:/sagittarius/public
#       - tmp-data:/sagittarius/tmp  
#     ports:
#       - "80:80"
#     depends_on:
#       - web
# volumes:
#   public-data:
#   tmp-data:
#   log-data:
#   db-data: