version: '3'
services:
  db:
    image: mysql:5.7.28
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gamepost01_development
      MYSQL_ROOT_PASSWORD: password
    tty: true
    ports:
      - 3306:3306
  
  rails:
    build:
      context: .
    volumes:
      - .:/gamepost01
      - public-data:/gamepost01/public
      - tmp-data:/gamepost01/tmp
      - log-data:/gamepost01/log
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
  nginx:
    build: 
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - rails
    volumes:
      - public-data:/gamepost01/public
      - tmp-data:/gamepost01/tmp
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql_data: